rename EvictionCause to RemovalCause
dgilland/cacheout pull request #33
Opened 2023-09-26 15:12 UTC by uncle-lv

In most caches([redis](https://redis.io/docs/reference/eviction/)、[caffeine](https://github.com/ben-manes/caffeine/wiki/Eviction) and etc.), eviction means the entry is removed due to `maxsize` limit. But `on_delete` callback will be executed in all removal cases. `EvictionCause` can lead to a misunderstanding, `RemovalCause` should be a better name.

2023-09-26 15:24 UTC, uncle-lv commented
Another reason is `expired_count` `evicted_count` `deleted_count` will be three different figures in statistics. But `EvictionCause` includes all three cases, what can lead to a misunderstanding too.

2023-09-28 20:29 UTC, dgilland requested changes
Just a minor nit to align the docstring of the class with the class rename.

2023-09-28 20:29 UTC, dgilland commented on src/cacheout/cache.py
>      An enum to represent the cause for the eviction of a cache entry.
nit: Can replace "eviction" with "removal".
```suggestion
    An enum to represent the cause for the removal of a cache entry.
```

2023-09-29 13:30 UTC, merged

2023-09-29 13:32 UTC, uncle-lv commented
Updated usage.

### Usage

set `on_delete` callback.

```python
cache = Cache(on_delete=on_delete)
```



`on_delete` is a callable object.

```python
Callable[[key: Hashable, value: Any, cause: RemovalCause],  None]
```

First parameter is the key of cache entry has been deleted. 

Second is the value. 

Third is the cause of cache entry removal.



`RemovalCause` is an enum.

```python
class RemovalCause(Enum):
    DELETE = auto()
    SET = auto()
    EXPIRED = auto()
    FULL = auto()
    POPITEM = auto()
```

- **DELETE**: indicates that the cache entry was deleted by delete() or delete_many() explicitly.
- **SET**: indicates that the cache entry was replaced with a new value by set() or set_many().
- **EXPIRED**: indicates that the cache entry was removed because it expired.
- **FULL**: indicates that the cache entry was removed because cache has been full (reached the maximum size limit).
- **POPITEM**: indicates that the cache entry was deleted by popitem().



### Trigger

The table shows methods will trigger `on_delete`.

|  cause  |                           trigger                            |
| :-----: | :----------------------------------------------------------: |
| DELETE  | The cache entry was removed explicitly by `delete()` or `delete_many()` |
|   SET   |   The cache entry was replaced by `set()` or `set_many()`    |
| POPITEM |          The cache entry was deleted by `popitem()`          |
| EXPIRED | **Implicit**. When the cache entry was removed because it expired |
|  FULL   | **Implicit**. The  cache entry was removed because cache has reached the maximum size limit |



⚠ `clear()` never triggers `on_delete`.